# Generated by Django 2.2.7 on 2020-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDB', '0008_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
