# Generated by Django 2.2.7 on 2020-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDB', '0009_auto_20200108_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='sws',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
