# Generated by Django 2.2.6 on 2019-10-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('genre', models.CharField(choices=[('a', 'Action'), ('c', 'Comedy')], max_length=1)),
                ('release_date', models.DateField()),
                ('plot', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='in Minutes')),
                ('black_and_white', models.BooleanField()),
                ('actors', models.ManyToManyField(to='yamod.Person')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.Country')),
            ],
        ),
    ]
