# Generated by Django 2.2.7 on 2019-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0003_auto_20191126_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='yamod.Person'),
        ),
    ]
